---
- name: Install Docker engine packages
  ansible.builtin.apt:
    name: "{{ apt_packages_docker_base }}"
    state: present

- name: Install Docker Compose plugin package
  ansible.builtin.apt:
    name: "{{ docker_compose_plugin_package }}"
    state: present

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    enabled: true
    state: started
  when: not ansible_check_mode
